package com.noc.monitor.ui

data class Copy(
    val app: String,
    val dashboard: String,
    val devices: String,
    val traffic: String,
    val alerts: String,
    val settings: String,
    val addDevice: String,
    val search: String,
    val all: String,
    val online: String,
    val offline: String,
    val unknown: String,
    val totalDevices: String,
    val totalTraffic: String,
    val highestTraffic: String,
    val noDevices: String,
    val noDevicesHint: String,
    val testConnection: String,
    val save: String,
    val host: String,
    val port: String,
    val username: String,
    val password: String,
    val displayName: String,
    val vendor: String,
    val family: String,
    val transport: String,
    val allowInsecure: String,
    val overview: String,
    val interfaces: String,
    val pppoe: String,
    val ip: String,
    val dhcp: String,
    val arp: String,
    val routes: String,
    val logs: String,
    val actions: String,
    val identity: String,
    val model: String,
    val version: String,
    val uptime: String,
    val cpu: String,
    val ram: String,
    val storage: String,
    val temperature: String,
    val running: String,
    val enabled: String,
    val disabled: String,
    val rx: String,
    val tx: String,
    val disconnect: String,
    val enable: String,
    val disable: String,
    val reboot: String,
    val confirm: String,
    val cancel: String,
    val confirmDisconnect: String,
    val confirmToggle: String,
    val confirmReboot1: String,
    val confirmReboot2: String,
    val unsupported: String,
    val lastResult: String,
    val language: String,
    val english: String,
    val arabic: String,
    val operatingMode: String,
    val realMode: String,
    val demoMode: String,
    val demoBanner: String,
    val realHint: String,
    val deleteDevice: String,
    val refresh: String,
    val fiveMin: String,
    val oneHour: String,
    val sixHours: String,
    val twentyFour: String,
    val noTraffic: String,
    val noAlerts: String,
    val ack: String,
    val packets: String,
    val none: String,
    val lastError: String,
    val peakOn: String,
    val polling: String,
)

val En = Copy(
    app = "NOC Monitor",
    dashboard = "Dashboard",
    devices = "Devices",
    traffic = "Traffic",
    alerts = "Alerts",
    settings = "Settings",
    addDevice = "Add device",
    search = "Search name, IP, identity",
    all = "All",
    online = "Online",
    offline = "Offline",
    unknown = "Unknown",
    totalDevices = "Total devices",
    totalTraffic = "Total traffic",
    highestTraffic = "Highest traffic device",
    noDevices = "No devices yet",
    noDevicesHint = "Add a MikroTik router with API, API-SSL or REST. REAL mode never invents traffic.",
    testConnection = "Test connection",
    save = "Save device",
    host = "IP / hostname",
    port = "API port",
    username = "Username",
    password = "Password",
    displayName = "Display name",
    vendor = "Vendor",
    family = "Product family",
    transport = "Transport",
    allowInsecure = "Allow self-signed TLS",
    overview = "Overview",
    interfaces = "Interfaces",
    pppoe = "PPPoE",
    ip = "IP",
    dhcp = "DHCP",
    arp = "ARP",
    routes = "Routes",
    logs = "Logs",
    actions = "Actions",
    identity = "Identity",
    model = "Model",
    version = "RouterOS",
    uptime = "Uptime",
    cpu = "CPU",
    ram = "RAM",
    storage = "Storage",
    temperature = "Temperature",
    running = "Running",
    enabled = "Enabled",
    disabled = "Disabled",
    rx = "RX",
    tx = "TX",
    disconnect = "Disconnect",
    enable = "Enable",
    disable = "Disable",
    reboot = "Reboot router",
    confirm = "Confirm",
    cancel = "Cancel",
    confirmDisconnect = "Disconnect this PPPoE session on the router?",
    confirmToggle = "Send a real interface set command to the router?",
    confirmReboot1 = "This will reboot the router. Continue?",
    confirmReboot2 = "Final confirmation: reboot the device now?",
    unsupported = "Unsupported",
    lastResult = "Last command result",
    language = "Language",
    english = "English",
    arabic = "العربية",
    operatingMode = "Operating mode",
    realMode = "REAL",
    demoMode = "DEMO",
    demoBanner = "DEMO MODE — data is local sample data, not a live network device",
    realHint = "REAL mode reads live counters from the device. Empty graphs mean the device has not been polled yet.",
    deleteDevice = "Remove device",
    refresh = "Refresh",
    fiveMin = "5 min",
    oneHour = "1 hour",
    sixHours = "6 hours",
    twentyFour = "24 hours",
    noTraffic = "No traffic samples in this window",
    noAlerts = "No alerts",
    ack = "Acknowledge",
    packets = "Packets",
    none = "None",
    lastError = "Last error",
    peakOn = "Peak on",
    polling = "Polling every 3 seconds",
)

val Ar = Copy(
    app = "مراقب الشبكة",
    dashboard = "لوحة التحكم",
    devices = "الأجهزة",
    traffic = "المرور",
    alerts = "التنبيهات",
    settings = "الإعدادات",
    addDevice = "إضافة جهاز",
    search = "بحث بالاسم أو العنوان أو الهوية",
    all = "الكل",
    online = "متصل",
    offline = "غير متصل",
    unknown = "غير معروف",
    totalDevices = "إجمالي الأجهزة",
    totalTraffic = "إجمالي المرور",
    highestTraffic = "أعلى جهاز مرورًا",
    noDevices = "لا توجد أجهزة",
    noDevicesHint = "أضف جهاز MikroTik عبر API أو API-SSL أو REST. الوضع الحقيقي لا يختلق بيانات المرور.",
    testConnection = "اختبار الاتصال",
    save = "حفظ الجهاز",
    host = "العنوان / الاسم",
    port = "منفذ API",
    username = "اسم المستخدم",
    password = "كلمة المرور",
    displayName = "اسم العرض",
    vendor = "الشركة",
    family = "عائلة المنتج",
    transport = "بروتوكول الاتصال",
    allowInsecure = "السماح بشهادة TLS ذاتية",
    overview = "نظرة عامة",
    interfaces = "المنافذ",
    pppoe = "PPPoE",
    ip = "عناوين IP",
    dhcp = "DHCP",
    arp = "ARP",
    routes = "التوجيه",
    logs = "السجلات",
    actions = "إجراءات",
    identity = "الهوية",
    model = "الطراز",
    version = "RouterOS",
    uptime = "زمن التشغيل",
    cpu = "المعالج",
    ram = "الذاكرة",
    storage = "التخزين",
    temperature = "الحرارة",
    running = "يعمل",
    enabled = "مفعّل",
    disabled = "معطّل",
    rx = "استقبال",
    tx = "إرسال",
    disconnect = "قطع الجلسة",
    enable = "تفعيل",
    disable = "تعطيل",
    reboot = "إعادة تشغيل الموجّه",
    confirm = "تأكيد",
    cancel = "إلغاء",
    confirmDisconnect = "قطع جلسة PPPoE على الموجّه؟",
    confirmToggle = "إرسال أمر حقيقي لتغيير حالة المنفذ؟",
    confirmReboot1 = "سيتم إعادة تشغيل الموجّه. متابعة؟",
    confirmReboot2 = "تأكيد نهائي: إعادة تشغيل الجهاز الآن؟",
    unsupported = "غير مدعوم",
    lastResult = "نتيجة آخر أمر",
    language = "اللغة",
    english = "English",
    arabic = "العربية",
    operatingMode = "وضع التشغيل",
    realMode = "حقيقي",
    demoMode = "تجريبي",
    demoBanner = "وضع تجريبي — البيانات محلية وليست من جهاز شبكة حي",
    realHint = "الوضع الحقيقي يقرأ العدادات من الجهاز. الرسم الفارغ يعني أنه لم يتم الجلب بعد.",
    deleteDevice = "حذف الجهاز",
    refresh = "تحديث",
    fiveMin = "٥ دقائق",
    oneHour = "ساعة",
    sixHours = "٦ ساعات",
    twentyFour = "٢٤ ساعة",
    noTraffic = "لا توجد عينات مرور في هذه النافذة",
    noAlerts = "لا توجد تنبيهات",
    ack = "إقرار",
    packets = "حزم",
    none = "لا يوجد",
    lastError = "آخر خطأ",
    peakOn = "الذروة على",
    polling = "جلب كل ٣ ثوانٍ",
)
